/* Auto-generated by genmsg_cpp for file /home/nemogiftsun/youBot/Edufill/components/edufill_sw/edufill_manipulation/edufill_arm_navigation/msg/MoveToJointConfigurationResult.msg */
#ifndef EDUFILL_ARM_NAVIGATION_MESSAGE_MOVETOJOINTCONFIGURATIONRESULT_H
#define EDUFILL_ARM_NAVIGATION_MESSAGE_MOVETOJOINTCONFIGURATIONRESULT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "arm_navigation_msgs/ArmNavigationErrorCodes.h"

namespace edufill_arm_navigation
{
template <class ContainerAllocator>
struct MoveToJointConfigurationResult_ {
  typedef MoveToJointConfigurationResult_<ContainerAllocator> Type;

  MoveToJointConfigurationResult_()
  : result()
  {
  }

  MoveToJointConfigurationResult_(const ContainerAllocator& _alloc)
  : result(_alloc)
  {
  }

  typedef  ::arm_navigation_msgs::ArmNavigationErrorCodes_<ContainerAllocator>  _result_type;
   ::arm_navigation_msgs::ArmNavigationErrorCodes_<ContainerAllocator>  result;


  typedef boost::shared_ptr< ::edufill_arm_navigation::MoveToJointConfigurationResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::edufill_arm_navigation::MoveToJointConfigurationResult_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct MoveToJointConfigurationResult
typedef  ::edufill_arm_navigation::MoveToJointConfigurationResult_<std::allocator<void> > MoveToJointConfigurationResult;

typedef boost::shared_ptr< ::edufill_arm_navigation::MoveToJointConfigurationResult> MoveToJointConfigurationResultPtr;
typedef boost::shared_ptr< ::edufill_arm_navigation::MoveToJointConfigurationResult const> MoveToJointConfigurationResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::edufill_arm_navigation::MoveToJointConfigurationResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::edufill_arm_navigation::MoveToJointConfigurationResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace edufill_arm_navigation

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::edufill_arm_navigation::MoveToJointConfigurationResult_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::edufill_arm_navigation::MoveToJointConfigurationResult_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::edufill_arm_navigation::MoveToJointConfigurationResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5aa3deb00fd4d3813dee18655cf173e8";
  }

  static const char* value(const  ::edufill_arm_navigation::MoveToJointConfigurationResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5aa3deb00fd4d381ULL;
  static const uint64_t static_value2 = 0x3dee18655cf173e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::edufill_arm_navigation::MoveToJointConfigurationResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "edufill_arm_navigation/MoveToJointConfigurationResult";
  }

  static const char* value(const  ::edufill_arm_navigation::MoveToJointConfigurationResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::edufill_arm_navigation::MoveToJointConfigurationResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# result\n\
arm_navigation_msgs/ArmNavigationErrorCodes result\n\
\n\
================================================================================\n\
MSG: arm_navigation_msgs/ArmNavigationErrorCodes\n\
int32 val\n\
\n\
# overall behavior\n\
int32 PLANNING_FAILED=-1\n\
int32 SUCCESS=1\n\
int32 TIMED_OUT=-2\n\
\n\
# start state errors\n\
int32 START_STATE_IN_COLLISION=-3\n\
int32 START_STATE_VIOLATES_PATH_CONSTRAINTS=-4\n\
\n\
# goal errors\n\
int32 GOAL_IN_COLLISION=-5\n\
int32 GOAL_VIOLATES_PATH_CONSTRAINTS=-6\n\
\n\
# robot state\n\
int32 INVALID_ROBOT_STATE=-7\n\
int32 INCOMPLETE_ROBOT_STATE=-8\n\
\n\
# planning request errors\n\
int32 INVALID_PLANNER_ID=-9\n\
int32 INVALID_NUM_PLANNING_ATTEMPTS=-10\n\
int32 INVALID_ALLOWED_PLANNING_TIME=-11\n\
int32 INVALID_GROUP_NAME=-12\n\
int32 INVALID_GOAL_JOINT_CONSTRAINTS=-13\n\
int32 INVALID_GOAL_POSITION_CONSTRAINTS=-14\n\
int32 INVALID_GOAL_ORIENTATION_CONSTRAINTS=-15\n\
int32 INVALID_PATH_JOINT_CONSTRAINTS=-16\n\
int32 INVALID_PATH_POSITION_CONSTRAINTS=-17\n\
int32 INVALID_PATH_ORIENTATION_CONSTRAINTS=-18\n\
\n\
# state/trajectory monitor errors\n\
int32 INVALID_TRAJECTORY=-19\n\
int32 INVALID_INDEX=-20\n\
int32 JOINT_LIMITS_VIOLATED=-21\n\
int32 PATH_CONSTRAINTS_VIOLATED=-22\n\
int32 COLLISION_CONSTRAINTS_VIOLATED=-23\n\
int32 GOAL_CONSTRAINTS_VIOLATED=-24\n\
int32 JOINTS_NOT_MOVING=-25\n\
int32 TRAJECTORY_CONTROLLER_FAILED=-26\n\
\n\
# system errors\n\
int32 FRAME_TRANSFORM_FAILURE=-27\n\
int32 COLLISION_CHECKING_UNAVAILABLE=-28\n\
int32 ROBOT_STATE_STALE=-29\n\
int32 SENSOR_INFO_STALE=-30\n\
\n\
# kinematics errors\n\
int32 NO_IK_SOLUTION=-31\n\
int32 INVALID_LINK_NAME=-32\n\
int32 IK_LINK_IN_COLLISION=-33\n\
int32 NO_FK_SOLUTION=-34\n\
int32 KINEMATICS_STATE_IN_COLLISION=-35\n\
\n\
# general errors\n\
int32 INVALID_TIMEOUT=-36\n\
\n\
\n\
";
  }

  static const char* value(const  ::edufill_arm_navigation::MoveToJointConfigurationResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::edufill_arm_navigation::MoveToJointConfigurationResult_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::edufill_arm_navigation::MoveToJointConfigurationResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.result);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MoveToJointConfigurationResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::edufill_arm_navigation::MoveToJointConfigurationResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::edufill_arm_navigation::MoveToJointConfigurationResult_<ContainerAllocator> & v) 
  {
    s << indent << "result: ";
s << std::endl;
    Printer< ::arm_navigation_msgs::ArmNavigationErrorCodes_<ContainerAllocator> >::stream(s, indent + "  ", v.result);
  }
};


} // namespace message_operations
} // namespace ros

#endif // EDUFILL_ARM_NAVIGATION_MESSAGE_MOVETOJOINTCONFIGURATIONRESULT_H

