/* Auto-generated by genmsg_cpp for file /home/nemogiftsun/youBot/Edufill/components/edufill_sw/edufill_manipulation/edufill_arm_navigation/msg/MoveToJointConfigurationActionGoal.msg */
#ifndef EDUFILL_ARM_NAVIGATION_MESSAGE_MOVETOJOINTCONFIGURATIONACTIONGOAL_H
#define EDUFILL_ARM_NAVIGATION_MESSAGE_MOVETOJOINTCONFIGURATIONACTIONGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "actionlib_msgs/GoalID.h"
#include "edufill_arm_navigation/MoveToJointConfigurationGoal.h"

namespace edufill_arm_navigation
{
template <class ContainerAllocator>
struct MoveToJointConfigurationActionGoal_ {
  typedef MoveToJointConfigurationActionGoal_<ContainerAllocator> Type;

  MoveToJointConfigurationActionGoal_()
  : header()
  , goal_id()
  , goal()
  {
  }

  MoveToJointConfigurationActionGoal_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , goal_id(_alloc)
  , goal(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
   ::actionlib_msgs::GoalID_<ContainerAllocator>  goal_id;

  typedef  ::edufill_arm_navigation::MoveToJointConfigurationGoal_<ContainerAllocator>  _goal_type;
   ::edufill_arm_navigation::MoveToJointConfigurationGoal_<ContainerAllocator>  goal;


  typedef boost::shared_ptr< ::edufill_arm_navigation::MoveToJointConfigurationActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::edufill_arm_navigation::MoveToJointConfigurationActionGoal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct MoveToJointConfigurationActionGoal
typedef  ::edufill_arm_navigation::MoveToJointConfigurationActionGoal_<std::allocator<void> > MoveToJointConfigurationActionGoal;

typedef boost::shared_ptr< ::edufill_arm_navigation::MoveToJointConfigurationActionGoal> MoveToJointConfigurationActionGoalPtr;
typedef boost::shared_ptr< ::edufill_arm_navigation::MoveToJointConfigurationActionGoal const> MoveToJointConfigurationActionGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::edufill_arm_navigation::MoveToJointConfigurationActionGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::edufill_arm_navigation::MoveToJointConfigurationActionGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace edufill_arm_navigation

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::edufill_arm_navigation::MoveToJointConfigurationActionGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::edufill_arm_navigation::MoveToJointConfigurationActionGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::edufill_arm_navigation::MoveToJointConfigurationActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5b80683170eaca6bd9e13ed4c57726a2";
  }

  static const char* value(const  ::edufill_arm_navigation::MoveToJointConfigurationActionGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5b80683170eaca6bULL;
  static const uint64_t static_value2 = 0xd9e13ed4c57726a2ULL;
};

template<class ContainerAllocator>
struct DataType< ::edufill_arm_navigation::MoveToJointConfigurationActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "edufill_arm_navigation/MoveToJointConfigurationActionGoal";
  }

  static const char* value(const  ::edufill_arm_navigation::MoveToJointConfigurationActionGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::edufill_arm_navigation::MoveToJointConfigurationActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
MoveToJointConfigurationGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: edufill_arm_navigation/MoveToJointConfigurationGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# goal\n\
brics_actuator/JointPositions goal\n\
\n\
================================================================================\n\
MSG: brics_actuator/JointPositions\n\
Poison poisonStamp\n\
JointValue[] positions\n\
\n\
================================================================================\n\
MSG: brics_actuator/Poison\n\
string originator 		# node id\n\
string description 		# encoding still an issue\n\
float32 qos			# reliability of the channel\n\
				# 0..1 where 1 means healthy\n\
\n\
================================================================================\n\
MSG: brics_actuator/JointValue\n\
time timeStamp 		#time of the data \n\
string joint_uri\n\
string unit 		#if empy expects si units, you can use boost::unit\n\
float64 value\n\
\n\
";
  }

  static const char* value(const  ::edufill_arm_navigation::MoveToJointConfigurationActionGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::edufill_arm_navigation::MoveToJointConfigurationActionGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::edufill_arm_navigation::MoveToJointConfigurationActionGoal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::edufill_arm_navigation::MoveToJointConfigurationActionGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.goal_id);
    stream.next(m.goal);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MoveToJointConfigurationActionGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::edufill_arm_navigation::MoveToJointConfigurationActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::edufill_arm_navigation::MoveToJointConfigurationActionGoal_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
s << std::endl;
    Printer< ::edufill_arm_navigation::MoveToJointConfigurationGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};


} // namespace message_operations
} // namespace ros

#endif // EDUFILL_ARM_NAVIGATION_MESSAGE_MOVETOJOINTCONFIGURATIONACTIONGOAL_H

