/* Auto-generated by genmsg_cpp for file /home/nemogiftsun/youBot/Edufill/components/edufill_sw/edufill_command_tools/edufill_script_server/msg/ScriptResult.msg */
#ifndef EDUFILL_SCRIPT_SERVER_MESSAGE_SCRIPTRESULT_H
#define EDUFILL_SCRIPT_SERVER_MESSAGE_SCRIPTRESULT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace edufill_script_server
{
template <class ContainerAllocator>
struct ScriptResult_ {
  typedef ScriptResult_<ContainerAllocator> Type;

  ScriptResult_()
  : error_code(0)
  {
  }

  ScriptResult_(const ContainerAllocator& _alloc)
  : error_code(0)
  {
  }

  typedef int32_t _error_code_type;
  int32_t error_code;


  typedef boost::shared_ptr< ::edufill_script_server::ScriptResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::edufill_script_server::ScriptResult_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ScriptResult
typedef  ::edufill_script_server::ScriptResult_<std::allocator<void> > ScriptResult;

typedef boost::shared_ptr< ::edufill_script_server::ScriptResult> ScriptResultPtr;
typedef boost::shared_ptr< ::edufill_script_server::ScriptResult const> ScriptResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::edufill_script_server::ScriptResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::edufill_script_server::ScriptResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace edufill_script_server

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::edufill_script_server::ScriptResult_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::edufill_script_server::ScriptResult_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::edufill_script_server::ScriptResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ea324a22c787839f822b9a025bc2c6fe";
  }

  static const char* value(const  ::edufill_script_server::ScriptResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xea324a22c787839fULL;
  static const uint64_t static_value2 = 0x822b9a025bc2c6feULL;
};

template<class ContainerAllocator>
struct DataType< ::edufill_script_server::ScriptResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "edufill_script_server/ScriptResult";
  }

  static const char* value(const  ::edufill_script_server::ScriptResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::edufill_script_server::ScriptResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
int32 error_code\n\
\n\
";
  }

  static const char* value(const  ::edufill_script_server::ScriptResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::edufill_script_server::ScriptResult_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::edufill_script_server::ScriptResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.error_code);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ScriptResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::edufill_script_server::ScriptResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::edufill_script_server::ScriptResult_<ContainerAllocator> & v) 
  {
    s << indent << "error_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.error_code);
  }
};


} // namespace message_operations
} // namespace ros

#endif // EDUFILL_SCRIPT_SERVER_MESSAGE_SCRIPTRESULT_H

