/* Auto-generated by genmsg_cpp for file /home/nemogiftsun/youBot/Edufill/components/edufill_sw/edufill_command_tools/edufill_script_server/msg/ScriptGoal.msg */
#ifndef EDUFILL_SCRIPT_SERVER_MESSAGE_SCRIPTGOAL_H
#define EDUFILL_SCRIPT_SERVER_MESSAGE_SCRIPTGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace edufill_script_server
{
template <class ContainerAllocator>
struct ScriptGoal_ {
  typedef ScriptGoal_<ContainerAllocator> Type;

  ScriptGoal_()
  : function_name()
  , component_name()
  , parameter_name()
  , mode()
  {
  }

  ScriptGoal_(const ContainerAllocator& _alloc)
  : function_name(_alloc)
  , component_name(_alloc)
  , parameter_name(_alloc)
  , mode(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _function_name_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  function_name;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _component_name_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  component_name;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _parameter_name_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  parameter_name;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mode_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  mode;


  typedef boost::shared_ptr< ::edufill_script_server::ScriptGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::edufill_script_server::ScriptGoal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ScriptGoal
typedef  ::edufill_script_server::ScriptGoal_<std::allocator<void> > ScriptGoal;

typedef boost::shared_ptr< ::edufill_script_server::ScriptGoal> ScriptGoalPtr;
typedef boost::shared_ptr< ::edufill_script_server::ScriptGoal const> ScriptGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::edufill_script_server::ScriptGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::edufill_script_server::ScriptGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace edufill_script_server

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::edufill_script_server::ScriptGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::edufill_script_server::ScriptGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::edufill_script_server::ScriptGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b8ba419c917044eefb668c2e3c0f4e65";
  }

  static const char* value(const  ::edufill_script_server::ScriptGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb8ba419c917044eeULL;
  static const uint64_t static_value2 = 0xfb668c2e3c0f4e65ULL;
};

template<class ContainerAllocator>
struct DataType< ::edufill_script_server::ScriptGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "edufill_script_server/ScriptGoal";
  }

  static const char* value(const  ::edufill_script_server::ScriptGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::edufill_script_server::ScriptGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
string function_name\n\
string component_name\n\
string parameter_name\n\
string mode\n\
\n\
";
  }

  static const char* value(const  ::edufill_script_server::ScriptGoal_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::edufill_script_server::ScriptGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.function_name);
    stream.next(m.component_name);
    stream.next(m.parameter_name);
    stream.next(m.mode);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ScriptGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::edufill_script_server::ScriptGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::edufill_script_server::ScriptGoal_<ContainerAllocator> & v) 
  {
    s << indent << "function_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.function_name);
    s << indent << "component_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.component_name);
    s << indent << "parameter_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.parameter_name);
    s << indent << "mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mode);
  }
};


} // namespace message_operations
} // namespace ros

#endif // EDUFILL_SCRIPT_SERVER_MESSAGE_SCRIPTGOAL_H

