/* Auto-generated by genmsg_cpp for file /home/nemogiftsun/youBot/Edufill/components/edufill_sw/edufill_command_tools/edufill_script_server/msg/ScriptFeedback.msg */
#ifndef EDUFILL_SCRIPT_SERVER_MESSAGE_SCRIPTFEEDBACK_H
#define EDUFILL_SCRIPT_SERVER_MESSAGE_SCRIPTFEEDBACK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace edufill_script_server
{
template <class ContainerAllocator>
struct ScriptFeedback_ {
  typedef ScriptFeedback_<ContainerAllocator> Type;

  ScriptFeedback_()
  {
  }

  ScriptFeedback_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::edufill_script_server::ScriptFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::edufill_script_server::ScriptFeedback_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ScriptFeedback
typedef  ::edufill_script_server::ScriptFeedback_<std::allocator<void> > ScriptFeedback;

typedef boost::shared_ptr< ::edufill_script_server::ScriptFeedback> ScriptFeedbackPtr;
typedef boost::shared_ptr< ::edufill_script_server::ScriptFeedback const> ScriptFeedbackConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::edufill_script_server::ScriptFeedback_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::edufill_script_server::ScriptFeedback_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace edufill_script_server

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::edufill_script_server::ScriptFeedback_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::edufill_script_server::ScriptFeedback_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::edufill_script_server::ScriptFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::edufill_script_server::ScriptFeedback_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::edufill_script_server::ScriptFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "edufill_script_server/ScriptFeedback";
  }

  static const char* value(const  ::edufill_script_server::ScriptFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::edufill_script_server::ScriptFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback definition\n\
\n\
\n\
";
  }

  static const char* value(const  ::edufill_script_server::ScriptFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::edufill_script_server::ScriptFeedback_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::edufill_script_server::ScriptFeedback_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ScriptFeedback_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::edufill_script_server::ScriptFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::edufill_script_server::ScriptFeedback_<ContainerAllocator> & v) 
  {
  }
};


} // namespace message_operations
} // namespace ros

#endif // EDUFILL_SCRIPT_SERVER_MESSAGE_SCRIPTFEEDBACK_H

