/* Auto-generated by genmsg_cpp for file /home/nemogiftsun/youBot/Edufill/components/edufill_sw/edufill_command_tools/edufill_script_server/msg/StateGoal.msg */
#ifndef EDUFILL_SCRIPT_SERVER_MESSAGE_STATEGOAL_H
#define EDUFILL_SCRIPT_SERVER_MESSAGE_STATEGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "edufill_script_server/ScriptState.h"

namespace edufill_script_server
{
template <class ContainerAllocator>
struct StateGoal_ {
  typedef StateGoal_<ContainerAllocator> Type;

  StateGoal_()
  : state()
  {
  }

  StateGoal_(const ContainerAllocator& _alloc)
  : state(_alloc)
  {
  }

  typedef  ::edufill_script_server::ScriptState_<ContainerAllocator>  _state_type;
   ::edufill_script_server::ScriptState_<ContainerAllocator>  state;


  typedef boost::shared_ptr< ::edufill_script_server::StateGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::edufill_script_server::StateGoal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct StateGoal
typedef  ::edufill_script_server::StateGoal_<std::allocator<void> > StateGoal;

typedef boost::shared_ptr< ::edufill_script_server::StateGoal> StateGoalPtr;
typedef boost::shared_ptr< ::edufill_script_server::StateGoal const> StateGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::edufill_script_server::StateGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::edufill_script_server::StateGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace edufill_script_server

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::edufill_script_server::StateGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::edufill_script_server::StateGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::edufill_script_server::StateGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5d2b1a5f7b8263c9eb024ed31a5dbee9";
  }

  static const char* value(const  ::edufill_script_server::StateGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5d2b1a5f7b8263c9ULL;
  static const uint64_t static_value2 = 0xeb024ed31a5dbee9ULL;
};

template<class ContainerAllocator>
struct DataType< ::edufill_script_server::StateGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "edufill_script_server/StateGoal";
  }

  static const char* value(const  ::edufill_script_server::StateGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::edufill_script_server::StateGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
edufill_script_server/ScriptState state\n\
\n\
================================================================================\n\
MSG: edufill_script_server/ScriptState\n\
Header header\n\
int16 number\n\
string function_name\n\
string component_name\n\
string parameter_name\n\
string full_graph_name\n\
\n\
# Possible execution states\n\
byte UNKNOWN=0\n\
byte ACTIVE=1\n\
byte SUCCEEDED=2\n\
byte FAILED=3\n\
byte PAUSED=4\n\
\n\
byte state # state of execution\n\
int16 error_code # current error_code for state\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::edufill_script_server::StateGoal_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::edufill_script_server::StateGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.state);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct StateGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::edufill_script_server::StateGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::edufill_script_server::StateGoal_<ContainerAllocator> & v) 
  {
    s << indent << "state: ";
s << std::endl;
    Printer< ::edufill_script_server::ScriptState_<ContainerAllocator> >::stream(s, indent + "  ", v.state);
  }
};


} // namespace message_operations
} // namespace ros

#endif // EDUFILL_SCRIPT_SERVER_MESSAGE_STATEGOAL_H

