; Auto-generated. Do not edit!


(cl:in-package edufill_arm_navigation-msg)


;//! \htmlinclude MoveToJointConfigurationGoal.msg.html

(cl:defclass <MoveToJointConfigurationGoal> (roslisp-msg-protocol:ros-message)
  ((goal
    :reader goal
    :initarg :goal
    :type brics_actuator-msg:JointPositions
    :initform (cl:make-instance 'brics_actuator-msg:JointPositions)))
)

(cl:defclass MoveToJointConfigurationGoal (<MoveToJointConfigurationGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveToJointConfigurationGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveToJointConfigurationGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name edufill_arm_navigation-msg:<MoveToJointConfigurationGoal> is deprecated: use edufill_arm_navigation-msg:MoveToJointConfigurationGoal instead.")))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <MoveToJointConfigurationGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader edufill_arm_navigation-msg:goal-val is deprecated.  Use edufill_arm_navigation-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveToJointConfigurationGoal>) ostream)
  "Serializes a message object of type '<MoveToJointConfigurationGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveToJointConfigurationGoal>) istream)
  "Deserializes a message object of type '<MoveToJointConfigurationGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveToJointConfigurationGoal>)))
  "Returns string type for a message object of type '<MoveToJointConfigurationGoal>"
  "edufill_arm_navigation/MoveToJointConfigurationGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveToJointConfigurationGoal)))
  "Returns string type for a message object of type 'MoveToJointConfigurationGoal"
  "edufill_arm_navigation/MoveToJointConfigurationGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveToJointConfigurationGoal>)))
  "Returns md5sum for a message object of type '<MoveToJointConfigurationGoal>"
  "474d9ddf2f29adac0f733d9f029bd72f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveToJointConfigurationGoal)))
  "Returns md5sum for a message object of type 'MoveToJointConfigurationGoal"
  "474d9ddf2f29adac0f733d9f029bd72f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveToJointConfigurationGoal>)))
  "Returns full string definition for message of type '<MoveToJointConfigurationGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%brics_actuator/JointPositions goal~%~%================================================================================~%MSG: brics_actuator/JointPositions~%Poison poisonStamp~%JointValue[] positions~%~%================================================================================~%MSG: brics_actuator/Poison~%string originator 		# node id~%string description 		# encoding still an issue~%float32 qos			# reliability of the channel~%				# 0..1 where 1 means healthy~%~%================================================================================~%MSG: brics_actuator/JointValue~%time timeStamp 		#time of the data ~%string joint_uri~%string unit 		#if empy expects si units, you can use boost::unit~%float64 value~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveToJointConfigurationGoal)))
  "Returns full string definition for message of type 'MoveToJointConfigurationGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%brics_actuator/JointPositions goal~%~%================================================================================~%MSG: brics_actuator/JointPositions~%Poison poisonStamp~%JointValue[] positions~%~%================================================================================~%MSG: brics_actuator/Poison~%string originator 		# node id~%string description 		# encoding still an issue~%float32 qos			# reliability of the channel~%				# 0..1 where 1 means healthy~%~%================================================================================~%MSG: brics_actuator/JointValue~%time timeStamp 		#time of the data ~%string joint_uri~%string unit 		#if empy expects si units, you can use boost::unit~%float64 value~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveToJointConfigurationGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveToJointConfigurationGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveToJointConfigurationGoal
    (cl:cons ':goal (goal msg))
))
