/* Auto-generated by genmsg_cpp for file /home/nemogiftsun/youBot/edufill_public/components/edufill_sw/edufill_common/edufill_srvs/srv/ExtractPlanes.srv */
#ifndef EDUFILL_SRVS_SERVICE_EXTRACTPLANES_H
#define EDUFILL_SRVS_SERVICE_EXTRACTPLANES_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"



#include "hbrs_msgs/PlanarPolygon.h"

namespace edufill_srvs
{
template <class ContainerAllocator>
struct ExtractPlanesRequest_ {
  typedef ExtractPlanesRequest_<ContainerAllocator> Type;

  ExtractPlanesRequest_()
  {
  }

  ExtractPlanesRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::edufill_srvs::ExtractPlanesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::edufill_srvs::ExtractPlanesRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ExtractPlanesRequest
typedef  ::edufill_srvs::ExtractPlanesRequest_<std::allocator<void> > ExtractPlanesRequest;

typedef boost::shared_ptr< ::edufill_srvs::ExtractPlanesRequest> ExtractPlanesRequestPtr;
typedef boost::shared_ptr< ::edufill_srvs::ExtractPlanesRequest const> ExtractPlanesRequestConstPtr;


template <class ContainerAllocator>
struct ExtractPlanesResponse_ {
  typedef ExtractPlanesResponse_<ContainerAllocator> Type;

  ExtractPlanesResponse_()
  : stamp()
  , planarpolygons()
  {
  }

  ExtractPlanesResponse_(const ContainerAllocator& _alloc)
  : stamp()
  , planarpolygons(_alloc)
  {
  }

  typedef ros::Time _stamp_type;
  ros::Time stamp;

  typedef std::vector< ::hbrs_msgs::PlanarPolygon_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::hbrs_msgs::PlanarPolygon_<ContainerAllocator> >::other >  _planarpolygons_type;
  std::vector< ::hbrs_msgs::PlanarPolygon_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::hbrs_msgs::PlanarPolygon_<ContainerAllocator> >::other >  planarpolygons;


  typedef boost::shared_ptr< ::edufill_srvs::ExtractPlanesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::edufill_srvs::ExtractPlanesResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ExtractPlanesResponse
typedef  ::edufill_srvs::ExtractPlanesResponse_<std::allocator<void> > ExtractPlanesResponse;

typedef boost::shared_ptr< ::edufill_srvs::ExtractPlanesResponse> ExtractPlanesResponsePtr;
typedef boost::shared_ptr< ::edufill_srvs::ExtractPlanesResponse const> ExtractPlanesResponseConstPtr;

struct ExtractPlanes
{

typedef ExtractPlanesRequest Request;
typedef ExtractPlanesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct ExtractPlanes
} // namespace edufill_srvs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::edufill_srvs::ExtractPlanesRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::edufill_srvs::ExtractPlanesRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::edufill_srvs::ExtractPlanesRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::edufill_srvs::ExtractPlanesRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::edufill_srvs::ExtractPlanesRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "edufill_srvs/ExtractPlanesRequest";
  }

  static const char* value(const  ::edufill_srvs::ExtractPlanesRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::edufill_srvs::ExtractPlanesRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::edufill_srvs::ExtractPlanesRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::edufill_srvs::ExtractPlanesRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::edufill_srvs::ExtractPlanesResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::edufill_srvs::ExtractPlanesResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::edufill_srvs::ExtractPlanesResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7a7315a968ecb96dca1d6bb20d5e284c";
  }

  static const char* value(const  ::edufill_srvs::ExtractPlanesResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x7a7315a968ecb96dULL;
  static const uint64_t static_value2 = 0xca1d6bb20d5e284cULL;
};

template<class ContainerAllocator>
struct DataType< ::edufill_srvs::ExtractPlanesResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "edufill_srvs/ExtractPlanesResponse";
  }

  static const char* value(const  ::edufill_srvs::ExtractPlanesResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::edufill_srvs::ExtractPlanesResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
time stamp\n\
\n\
\n\
hbrs_msgs/PlanarPolygon[] planarpolygons\n\
\n\
\n\
\n\
================================================================================\n\
MSG: hbrs_msgs/PlanarPolygon\n\
# This message is a wrapper for the PCL datatype PlanarPolygon.\n\
# http://docs.pointclouds.org/trunk/classpcl_1_1_planar_polygon.html\n\
\n\
# Plane coefficients\n\
float32[4] coefficients\n\
# List of points in the contour\n\
geometry_msgs/Point32[] contour\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const  ::edufill_srvs::ExtractPlanesResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::edufill_srvs::ExtractPlanesRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ExtractPlanesRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::edufill_srvs::ExtractPlanesResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.stamp);
    stream.next(m.planarpolygons);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ExtractPlanesResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<edufill_srvs::ExtractPlanes> {
  static const char* value() 
  {
    return "7a7315a968ecb96dca1d6bb20d5e284c";
  }

  static const char* value(const edufill_srvs::ExtractPlanes&) { return value(); } 
};

template<>
struct DataType<edufill_srvs::ExtractPlanes> {
  static const char* value() 
  {
    return "edufill_srvs/ExtractPlanes";
  }

  static const char* value(const edufill_srvs::ExtractPlanes&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<edufill_srvs::ExtractPlanesRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7a7315a968ecb96dca1d6bb20d5e284c";
  }

  static const char* value(const edufill_srvs::ExtractPlanesRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<edufill_srvs::ExtractPlanesRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "edufill_srvs/ExtractPlanes";
  }

  static const char* value(const edufill_srvs::ExtractPlanesRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<edufill_srvs::ExtractPlanesResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7a7315a968ecb96dca1d6bb20d5e284c";
  }

  static const char* value(const edufill_srvs::ExtractPlanesResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<edufill_srvs::ExtractPlanesResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "edufill_srvs/ExtractPlanes";
  }

  static const char* value(const edufill_srvs::ExtractPlanesResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // EDUFILL_SRVS_SERVICE_EXTRACTPLANES_H

